//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CornerFishing.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class News
    {
        public int Id { get; set; }
        public string Headline { get; set; }
        public string NewsText { get; set; }
        public Nullable<System.DateTime> NewsDate { get; set; }
        public Nullable<int> Order { get; set; }
        public Nullable<int> EventID { get; set; }
        public string ImageLink { get; set; }
        public Nullable<bool> FrontPage { get; set; }
    }
}
