//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CornerFishing.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sponsor
    {
        public int Id { get; set; }
        public string Sponsor1 { get; set; }
        public string Phone { get; set; }
        public string LogoPath { get; set; }
        public string Notes { get; set; }
        public string URL { get; set; }
        public bool Active { get; set; }
    }
}
